version: '3.8'

services:
  db:
    image: postgres
    container_name: local_pgdbb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - local_pgdata:/var/lib/postgresql/dataa
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_containerr
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadminn

  booksharingapp:
    depends_on:
      - db
    image: msorunga/booksharing:latest
    restart: always
    build:
      context: .
    ports:
      - "5000:5000"
      
volumes:
  local_pgdata:
  pgadmin-data:
