version: '3.8'

services:
   db:
     image: postgres:latest
     ports:
       - "5432"
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
     volumes:
       - db_volume:/var/lib/postgresql/data
     restart: always

   booksharingapp:
     depends_on:
       - db
     image: booksharing:runtime
     build:
       context: .
     ports:
       - "8080:5000"
volumes:
  db_volume:
