version: '3.8'

services:
   db:
     container_name: pg_container
     image: postgres:latest
     restart: always
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
     volumes:
       - db_volume:/var/lib/postgresql/data
     ports:
       - "5432:5432"

   pgadmin:
     container_name: pgadmin4_container
     image: dpage/pgadmin4
     restart: always
     environment:
       PGADMIN_DEFAULT_EMAIL: admin@admin.com
       PGADMIN_DEFAULT_PASSWORD: root
     volumes:
       - pgadmin:/var/lib/pgadmin
     ports:
       - "5050:80"

   booksharingapp:
     depends_on:
       - db
     image: booksharing:runtime
     restart: always
     build:
       context: .
     ports:
       - "5000:5000"
volumes:
  db_volume:
  pgadmin:
